# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chk_omp <- function() {
    .Call('_copre_chk_omp', PACKAGE = 'copre')
}

copre_cpp <- function(y_perm, alpha, rho, N, k, P, grd, nthreads) {
    .Call('_copre_copre_cpp', PACKAGE = 'copre', y_perm, alpha, rho, N, k, P, grd, nthreads)
}

mdp_cpp <- function(y, k, alpha, mu, tau, s, S, c, C, a, A, w, W, fix_a, fix_m, fix_t, burn, thin) {
    .Call('_copre_mdp_cpp', PACKAGE = 'copre', y, k, alpha, mu, tau, s, S, c, C, a, A, w, W, fix_a, fix_m, fix_t, burn, thin)
}

polyaurn_cpp <- function(theta, hyper, eps, ups, nthreads) {
    .Call('_copre_polyaurn_cpp', PACKAGE = 'copre', theta, hyper, eps, ups, nthreads)
}

mpy_cpp <- function(y, k, d, alpha, mu, tau, s, S, c, C, a, A, w, W, fix_a, fix_m, fix_t, burn, thin) {
    .Call('_copre_mpy_cpp', PACKAGE = 'copre', y, k, d, alpha, mu, tau, s, S, c, C, a, A, w, W, fix_a, fix_m, fix_t, burn, thin)
}

polyaurngen_cpp <- function(theta, alpha, eps, ups, nthreads) {
    .Call('_copre_polyaurngen_cpp', PACKAGE = 'copre', theta, alpha, eps, ups, nthreads)
}

evalmdpolya_cpp <- function(mdpolya, x, f, nthreads) {
    .Call('_copre_evalmdpolya_cpp', PACKAGE = 'copre', mdpolya, x, f, nthreads)
}

