# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chk_omp <- function() {
    .Call('_copre_chk_omp', PACKAGE = 'copre')
}

copre_cpp <- function(y_perm, alpha, rho, N, k, P, grd, nthreads) {
    .Call('_copre_copre_cpp', PACKAGE = 'copre', y_perm, alpha, rho, N, k, P, grd, nthreads)
}

marg_cpp <- function(y, k, z0, bas_idx, bas_pars, bas_hpars, seq_idx, seq_pars, seq_hpars, burn, thin) {
    .Call('_copre_marg_cpp', PACKAGE = 'copre', y, k, z0, bas_idx, bas_pars, bas_hpars, seq_idx, seq_pars, seq_hpars, burn, thin)
}

seqre_cpp <- function(phi, n, bas_idx, bas_pars, bas_hpars, seq_idx, seq_pars, seq_hpars, eps, inc, max_it) {
    .Call('_copre_seqre_cpp', PACKAGE = 'copre', phi, n, bas_idx, bas_pars, bas_hpars, seq_idx, seq_pars, seq_hpars, eps, inc, max_it)
}

